### ISSUE TITLE
meta: consider combining crates

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#308]
### Motivation

`tracing` currently consists of a large number of crates. The number of crates has the potential to be quite intimidating to users. 

### Proposal

We should consider collapsing several of the `tracing` crates into larger crates with feature flags. 

#### Some crates which can probably be folded together:
- [x] `tracing-fmt` could be a feature-flagged module in `tracing-subscriber`
- [ ] `tracing-env-logger` could be a feature of `tracing-log` (or removed?)
- [ ] `tracing-tower-http` is already a feature flag of `tracing-tower` and should thus be removed.

#### Crates which we cannot combine:
- `tracing`, `tracing-core`, and `tracing-subscriber` should remain separate, as they represent three decoupled clusters of responsibility. In particular, keeping the core facade layer separate from both `tracing` and `subscriber` is important for compatibility
- the `tracing-attributes` crate (and other future proc-macro crates) can be re-exported by other crates, but cannot be _combined_; proc-macros must be defined by crates that only define proc-macros

#### Stuff I'm on the fence about:
- What to do with crates that are specifically for integrating with other projects/ecosystems?  
 * For example, consider `tracing-tower`. If this was moved into `tracing`, it would almost certainly have to be a default-off feature, since not all `tracing` users are also using `tower`. But a default-off feature is significantly less discoverable than a separate crate, especially since `docs.rs` builds docs for only the default feature set.
- `tracing-futures`. Futures are commonly used enough that they could be moved into `tracing`, and the `std-future` support could be moved to `tracing` without adding another dependency (optional or otherwise).  It's unclear to me whether or not we should do this.
- `tracing-log`

### Alternatives

We could also choose not to do this, and continue with the current number of crates. I think this has some disadvantages in terms of code duplication and user experience, and the Tokio ecosystem proper is moving away from the "a lot of small crates" model. I'm open to hearing arguments in favour of leaving the current number of crates, but I think simplifying the ecosystem at least somewhat is almost certainly the right move.

**Comment by hawkw** [comment]
cc @tokio-rs/tracing, @carllerche, et al.

**Comment by LucioFranco** [comment]
I think it makes sense to bundle things like tower-http and tower, and log and env-logger. But I do think each kinda separate thing like tower etc should be in their own crate and keep tracing itself light.
