### ISSUE TITLE
core: tracking issue for `tracing-core` 0.2 breaking changes

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#922]
### Crates

- `tracing-core`

### Motivation

In order to reduce churn throughout the ecosystem, we intend to synchronize the `tokio` 0.3 and `tracing-core` 0.2 releases. This issue will track and discuss `tracing-core` 0.2 breaking changes.

### Minor API Tweaks

These are low-hanging fruit API changes that don't require a great deal of work, but can't be changed without breaking existing APIs.

- [ ] Make arguments to `set_default` and `set_global_default` consistent (#455)
- [ ] Consider changing `Event` struct to have non-`'static` metadata (`Cow`?) (needs issue)
- [ ] Rename `Subscriber` -> `Collector` (so that `Layer` -> `Subscriber` in `tracing-subscriber` (#641)

### Metadata/Callsite improvements

- [ ] Investigate removing cyclic `Metadata` <-> `Callsite` reference (needs issue)
- [ ] Consider using `Cow<str, 'static>` for `Metadata` strings rather than `&'static str` (needs issue)

### Value System Improvements

See RFC for `ValueSet` ergonomics improvements #697.

- [ ] Rework `ValueSet`s to support indexing as well as visiting  (needs issue)
- [ ] Consider changing `Value` to dispatch primitives w/ an enum rather than trait objects (needs issue)
- [ ] Figure out #782  while we're messing with `ValueSet`s

**Comment by hawkw** [comment]
There are also a handful of proposed changes which don't appear to inherently require breaking API changes, but *may* not be possible to implement without breaking changes (or could be implemented more easily with breaking changes). It would be worth doing further investigation of those proposed changes while we have the opportunity to break things for 0.2.

These include:
- [ ] #921 (probably much _easier_ if we figure out a good way to remove the cyclical callsite/metadata reference)
- [ ] #860

**Comment by hawkw** [comment]
There are probably other issues and proposed changes I've missed, both on the lists of definite breaking changes, and on the list of proposed changes that should be investigated prior to shipping a breaking release. If anyone can think of anything I've left out, please post them here!

**Comment by hawkw** [comment]
Opened #1262 for removing some default method impls from `Collect` that were initially added for backwards compatibility when adding new methods.

**Comment by carllerche** [comment]
I believe there was some discussion about changing the Subscriber/Collector trait to enable avoiding map lookups when handling events. Is that reflected yet? If not, I am leaving the comment so we don't forget :smile: .

**Comment by hawkw** [comment]
> I believe there was some discussion about changing the Subscriber/Collector trait to enable avoiding map lookups when handling events. Is that reflected yet? If not, I am leaving the comment so we don't forget smile .

There isn't an issue for that yet --- I *thought* you said you were going to write a proposal for it, but I may have misremembered that. I can try to write one if you'd prefer?

**Comment by carllerche** [comment]
I can write a proposal, but we should have a placeholder issue until then :)
